<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Login Form</title>
  <link rel="stylesheet" href="/public/css/log-style.css">
  <!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>

  <section class="container">
    <div class="login">
      <h1>用户登录</h1>
      <form method="post" >
        <p><input type="text" name="uname" value="" placeholder="帐号"></p>
        <p><input type="password" name="password" value="" placeholder="密码"></p>
        <p class="remember_me">
          <label>
            <input type="checkbox" name="remember_me" id="remember_me">
            记住密码
          </label>
        </p>
        <p class="submit"><input type="submit" name="commit" value="登录"></p>
      </form>
    </div>

    <div class="login-help">
      <p>没有帐号? <a href="register">返回注册</a>.</p>
    </div>
  </section>

</body>
<script type="text/javascript" src="/public/js/jquery.js"></script>
<script>
    $("input[name=commit]").click(function(){
        $.ajax({
            url: '/index.php/login/checklogin',
            type: 'post',
            data: {
                uname: $('input[name=uname]').val(),
                password: $('input[name=password]').val(),
            },
            datatype: 'json',
            success: function(data){
                var obj = eval('(' + data + ')'); 
                if(obj.code==200){
                    location.href='user';
                }else{
                    alert(obj.msg);
                }
            }
            
        })
        return false;
    })
</script>
</html>
