<!DOCTYPE html>
<html>
<head>
<title>注册</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
<link rel="shortcut icon" href="/public/img/favicon.ico" />
<link href="/public/css/reg-style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/public/js/jquery.js"></script>
<script type="text/javascript" src="/public/js/jquery.i18n.properties-1.0.9.js" ></script>
<script type="text/javascript" src="/public/js/jquery-ui-1.10.3.custom.js"></script>
<script type="text/javascript" src="/public/js/jquery.validate.js"></script>
<script type="text/javascript" src="/public/js/md5.js"></script>
<script type="text/javascript" src="/public/js/page_regist.js?lang=zh"></script>
<!--[if IE]>
  <script src="/public/js/html5.js"></script>
<![endif]-->
<!--[if lte IE 6]>
    <script src="/public/js/DD_belatedPNG_0.0.8a-min.js" language="javascript"></script>
    <script>
      DD_belatedPNG.fix('div,li,a,h3,span,img,.png_bg,ul,input,dd,dt');
    </script>
<![endif]-->
</head>
<body class="loginbody">
<div class="dataEye">
    <div class="loginbox registbox">
        <div class="login-content reg-content">
            <div class="loginbox-title">
                <h3>注册</h3>
            </div>
            <form id="signupForm">
            <div class="login-error"></div>
            <div class="row">
                <label class="field" for="uname">注册帐号</label>
                <input type="text" value="" class="input-text-user noPic input-click" name="uname" id="uname">
            </div>
            <div class="row">
                <label class="field" for="password">密码</label>
                <input type="password" value="" class="input-text-password noPic input-click" name="password" id="password">
            </div>
            <div class="row">
                <label class="field" for="passwordAgain">确认密码</label>
                <input type="password" value="" class="input-text-password noPic input-click" name="passwordAgain" id="passwordAgain">
            </div>
            <div class="row">
                <label class="field" for="realname">姓名</label>
                <input type="text" value="" class="input-text-user noPic input-click" name="realname" id="realname">
            </div>
            <div class="row">
                <label class="field" for="idcard">身份证</label>
                <input type="text" value="" class="input-text-user noPic input-click" name="idcard" id="idcard">
            </div>
            <div class="row tips">
                <input type="checkbox" id="checkBox">
                <label>
                我已阅读并同意
                <a href="#" target="_blank">隐私政策、服务条款</a>
                </label>
            </div>
            <div class="row btnArea">
                <a class="login-btn" id="submit" style="color:red">注册</a>
            </div>
            </form>
        </div>
        <div class="go-regist">
            已有帐号,请<a href="login" class="link">登录</a>
        </div>
    </div>
    
</div>
<div class="loading">
    <div class="mask">
        <div class="loading-img">
        <img src="/public/img/loading.gif" width="31" height="31">
        </div>
    </div>
</div>
</body>
</html>

