<?php include "common/head.html";?>
<div class='container'>
    <form class="form-horizontal">
        <div class="control-group">
            <label class="control-label" for="bankname">
                银行名
            </label>
            <div class="controls">
                <input type="text" id="bankname" name='bankname' value='<?php echo $data['bname']; ?>' placeholder="bankname">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="bankmark">
                银行代码
            </label>
            <div class="controls">
                <input type="text" id="bankmark" name='bankmark' value='<?php echo $data['bmark']; ?>' placeholder="bankmark">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputPassword">
                银行信息
            </label>
            <div class="controls">
                <textarea rows="5" id='bankinfo' name="bankinfo" placeholder="bankinfo"><?php echo $data['binfo']; ?></textarea>
            </div>
        </div>
        <input type='hidden' value='<?php echo $data['bid']; ?>' name='bankid' id='bankid' >
        <div class="control-group">
            <div class="controls">
                <button type="button" class="btn">
                   保存
                </button>
            </div>
        </div>
    </form>
</div>
<script>
    $('.btn').click(function(){
        if($('#bankname').val()=='' || $('#bankmark').val()=='' || $('#bankinfo').val()==''){
            alert("请全部填写");
            return false;
        }
        var url = '/index.php/admin/addbank';
        if($('input[name=bankid]').val()!=''){
            url = '/index.php/admin/editbank';
        }        
        $.ajax({
            url: url,
            type: "POST",
            data: {
                bankid  : $('#bankid').val(),
                bankname: $('#bankname').val(),
                bankmark: $('#bankmark').val(),
                bankinfo: $('#bankinfo').val(),
            },
            dataType: 'json',
            success: function(data){
                alert(data.msg);
                if(data.code==5){
                    window.location.reload();
                }         
            }
        })
    })
</script>
<?php include "common/foot.html";?>