<?php include "common/head.html";?>
<div class='container'>
    <canvas id="Chart" width="400" height="200"></canvas>
</div>
<script>
    var randomScalingFactor = function(){ return Math.round(Math.random()*100)};
    var lineChartData = {
        //labels : ["January","February","March","April","May","June","July"],
        labels : [<?php echo $data['bname'];?>],
        datasets : [
            {//成交单数
                label: "成交单数",
                fillColor : "rgba(20,60,50,0.5)",
                strokeColor : "rgba(220,220,220,1)",
                pointColor : "rgba(220,220,220,1)",
                pointStrokeColor : "#eee",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(220,220,220,1)",
                data : [<?php echo $data['count'];?>]
            },
            {//成交总金额
                label: "成交总金额",
                fillColor : "rgba(151,187,205,0.2)",
                strokeColor : "rgba(151,187,205,1)",
                pointColor : "rgba(151,187,205,1)",
                pointStrokeColor : "#ddd",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(151,187,205,1)",
                data : [<?php echo $data['money'];?>]
            },
            {//成交订单扣除手续费
                label: "支付商手续费",
                fillColor : "rgba(120,130,140,0.3)",
                strokeColor : "rgba(0,0,0,1)",
                pointColor : "rgba(110,120,220,1)",
                pointStrokeColor : "#bbb",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(220,220,220,1)",
                data : [<?php echo $data['poundage'];?>]
            },
            
            
            /*,
            {
                label: "My Second dataset",
                fillColor : "rgba(151,187,205,0.2)",
                strokeColor : "rgba(151,187,205,1)",
                pointColor : "rgba(151,187,205,1)",
                pointStrokeColor : "#fff",
                pointHighlightFill : "#fff",
                pointHighlightStroke : "rgba(151,187,205,1)",
                data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
                //data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
            }*/
        ]

    }

    window.onload = function(){
        var ctx = document.getElementById("Chart").getContext("2d");
        window.myLine = new Chart(ctx).Line(lineChartData, {
            responsive: true
        });
    }


</script>
<?php include "common/foot.html";?>